<?xml version="1.0" encoding="utf-8"?><Database Name="BazaWakeMeOnLan" Class="DataClassesDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="AppSettings" ConnectionString="Data Source=(LocalDB)\MSSQLLocalDB;AttachDbFilename=C:\Users\asiak\Documents\BazaWakeMeOnLan.mdf;Integrated Security=True;Connect Timeout=30" SettingsObjectName="WakeMeOnLan.Properties.Settings" SettingsPropertyName="BazaWakeMeOnLanConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.Siec" Member="Siec">
    <Type Name="Siec">
      <Column Name="Id" Type="System.Int32" DbType="Int NOT NULL IDENTITY" IsPrimaryKey="true" IsDbGenerated="true" CanBeNull="false" />
      <Column Name="Adres_IP" Type="System.String" DbType="NVarChar(15) NOT NULL" CanBeNull="false" />
      <Column Name="Adres_MAC" Type="System.String" DbType="NVarChar(17) NOT NULL" CanBeNull="false" />
      <Column Name="Czy_uspiony" Type="System.Int32" DbType="Int NOT NULL" CanBeNull="false" />
    </Type>
  </Table>
</Database>